credentials:
  usernames:
    Daveroonie: # This line needs to be indented by 4 spaces (2 levels of 2 spaces, or 1 level of 4 spaces if you prefer)
      email: dummyemail@example.com
      name: Dave
      password: 7vwxAyvjY6
cookie:
  expiry_days: 30
  key: 195c7cbcfa646c6510a1b9c9a76718bf732f9d82afc65855aa21f1052f2ae56f
  name: dave_habit_tracker_cookie
preauthorized:
  emails: []